version: '3.9'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_SERVE_STATIC_FILES: 'true'
    depends_on:
      - track_db
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    stdin_open: true
  track_db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  db-data:
