version: '3.9'
services:
  web:
    build:
      context: .
      target: ${RAILS_ENV:-production}
    volumes:
      - .:/app
    ports:
      - "80:3000"
      - "443:3000"
    depends_on:
      - track_db
    tty: true
    stdin_open: true
    env_file:
      - .env
  track_db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  db-data:
