# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: "<%= ENV.fetch("RDS_DB_NAME") { "app" } %>"
  username: "<%= ENV.fetch("RDS_USERNAME") { "app" } %>"
  password: "<%= ENV.fetch("RDS_PASSWORD") { "password" } %>"
  host: "<%= ENV.fetch("RDS_HOSTNAME") { "track_db" } %>"
  port: "<%= ENV.fetch("RDS_PORT") { 5432 } %>"

development:
  <<: *default
  database: <%= ENV.fetch("RDS_DB_NAME") { "app" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("RDS_DB_NAME") { "app" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("RDS_DB_NAME") %>
